remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: Ксю | Виртуальная подруга 24/7
# description: Мой сайт на GitHub Pages

show_downloads: false
github:
  is_project_page: false
